### PR TITLE
manifest: Allow CrOS Terminal app as a client.

### PR DESCRIPTION
**Pull request by matthew-0-1**
https://github.com/google/chrome-ssh-agent/issues/159

### CODE REVIEW

**Comment by matthew-0-1** [comment]
I noticed the actual `cla/google` workflow approval status is not public, while the error comment from `google-cla` bot is.  This is not blocked on `cla/google` anymore.

**Review by ralimi — APPROVED** [review]

**Comment by ralimi** [comment]
We have a requiement for this repository that all commits be signed, and merging is blocked on that.

Would it be possible to recreate this with a signed commit?  Alternatively, I could patch in and submit if you would like.

**Comment by ralimi** [comment]
I'll go ahead and patch this in to move this forward.  Appreciate the contribution!

**Comment by ralimi** [comment]
This was patched in as #171 .  Thank you @matthew-0-1 for the contribution!

**Pull request closed without merging**
